### ISSUE TITLE
Please upload solution 

### ISSUE THREAD

**Issue by DLND8** [hettval1/cma-week2#1]
Can you please upload your solution for week 2. Thanks!

**Comment by hettval1** [comment]
Hi Dominic

I couldnt complete the task, but I uploaded it now. Sorry, I didnt know how to handle it with git hub.

**Comment by DLND8** [comment]
We have uploaded the solutions here: https://computationalmovementanalysis.github.io/FS23/Week2/W2_6_solutions.html. Please have a close look and if you have open questions please let us know. And please update your solution accordingly. As exercise 2 and 3 are assessments (pass /no pass), we expect a  more thoroughly worked out solution for exercise 3.
